{% set name = "yarl" %}
{% set version = "1.3.0" %}
{% set sha256 = "024ecdc12bc02b321bc66b41327f930d1c2c543fa9a561b39861da9388ba7aa9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - multidict >=4.0
    - idna >=2.0

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - py.test tests

about:
  home: https://github.com/aio-libs/yarl
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Yet another URL library
  doc_url: http://yarl.readthedocs.io
  dev_url: https://github.com/aio-libs/yarl
  doc_source_url: https://github.com/aio-libs/yarl/tree/master/docs

extra:
  recipe-maintainers:
    - sodre
